CREATE OR REPLACE PACKAGE PKG_PRODUCTOS AS
  PROCEDURE CREAR_PRODUCTO(p_nombre VARCHAR2, p_stock NUMBER, p_id_categoria NUMBER);
  PROCEDURE ACTUALIZAR_PRODUCTO(p_id NUMBER, p_nombre VARCHAR2, p_stock NUMBER, p_id_categoria NUMBER);
  PROCEDURE ELIMINAR_PRODUCTO(p_id NUMBER);
  PROCEDURE OBTENER_PRODUCTO(p_id NUMBER, p_result OUT SYS_REFCURSOR);
  PROCEDURE LISTAR_PRODUCTOS(p_result OUT SYS_REFCURSOR);
END PKG_PRODUCTOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_PRODUCTOS AS
  PROCEDURE CREAR_PRODUCTO(p_nombre VARCHAR2, p_stock NUMBER, p_id_categoria NUMBER) IS
  BEGIN
    INSERT INTO PRODUCTO(NOMBRE, STOCK, ID_CATEGORIA)
    VALUES (p_nombre, p_stock, p_id_categoria);
  END;

  PROCEDURE ACTUALIZAR_PRODUCTO(p_id NUMBER, p_nombre VARCHAR2, p_stock NUMBER, p_id_categoria NUMBER) IS
  BEGIN
    UPDATE PRODUCTO
    SET NOMBRE = p_nombre, STOCK = p_stock, ID_CATEGORIA = p_id_categoria
    WHERE ID = p_id;
  END;

  PROCEDURE ELIMINAR_PRODUCTO(p_id NUMBER) IS
  BEGIN
    DELETE FROM PRODUCTO WHERE ID = p_id;
  END;

  PROCEDURE OBTENER_PRODUCTO(p_id NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR SELECT * FROM PRODUCTO WHERE ID = p_id;
  END;

  PROCEDURE LISTAR_PRODUCTOS(p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR SELECT * FROM PRODUCTO;
  END;
END PKG_PRODUCTOS;
/