CREATE OR REPLACE PACKAGE PKG_UTILIDADES AS
  PROCEDURE PRODUCTOS_CON_STOCK_BAJO(p_umbral NUMBER, p_result OUT SYS_REFCURSOR);
END PKG_UTILIDADES;
/

CREATE OR REPLACE PACKAGE BODY PKG_UTILIDADES AS
  PROCEDURE PRODUCTOS_CON_STOCK_BAJO(p_umbral NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR
      SELECT * FROM PRODUCTO WHERE STOCK < p_umbral;
  END;
END PKG_UTILIDADES;
/
