CREATE OR REPLACE PACKAGE PKG_CATEGORIAS AS
  PROCEDURE CREAR_CATEGORIA(p_nombre VARCHAR2);
  PROCEDURE ACTUALIZAR_CATEGORIA(p_id NUMBER, p_nombre VARCHAR2);
  PROCEDURE ELIMINAR_CATEGORIA(p_id NUMBER);
  PROCEDURE OBTENER_CATEGORIA(p_id NUMBER, p_result OUT SYS_REFCURSOR);
  PROCEDURE LISTAR_CATEGORIAS(p_result OUT SYS_REFCURSOR);
END PKG_CATEGORIAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_CATEGORIAS AS
  PROCEDURE CREAR_CATEGORIA(p_nombre VARCHAR2) IS
  BEGIN
    INSERT INTO CATEGORIA(NOMBRE) VALUES (p_nombre);
  END;

  PROCEDURE ACTUALIZAR_CATEGORIA(p_id NUMBER, p_nombre VARCHAR2) IS
  BEGIN
    UPDATE CATEGORIA SET NOMBRE = p_nombre WHERE ID = p_id;
  END;

  PROCEDURE ELIMINAR_CATEGORIA(p_id NUMBER) IS
  BEGIN
    DELETE FROM CATEGORIA WHERE ID = p_id;
  END;

  PROCEDURE OBTENER_CATEGORIA(p_id NUMBER, p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR SELECT * FROM CATEGORIA WHERE ID = p_id;
  END;

  PROCEDURE LISTAR_CATEGORIAS(p_result OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_result FOR SELECT * FROM CATEGORIA;
  END;
END PKG_CATEGORIAS;
/
