CREATE OR REPLACE PACKAGE PKG_AUTENTICACION AS
  FUNCTION VALIDAR_USUARIO(p_username VARCHAR2, p_password_hash VARCHAR2) RETURN BOOLEAN;
END PKG_AUTENTICACION;
/

CREATE OR REPLACE PACKAGE BODY PKG_AUTENTICACION AS
  FUNCTION VALIDAR_USUARIO(p_username VARCHAR2, p_password_hash VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
    FROM USUARIO
    WHERE USERNAME = p_username AND PASSWORD_HASH = p_password_hash;

    RETURN v_count > 0;
  END;
END PKG_AUTENTICACION;
/
