spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.147:1521:XE
    username: system
    password: Leito9803
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

server:
  port: 8081