quarkus:
  http:
    port: 8081
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated

  datasource:
    db-kind: oracle
    username: system
    password: Leito9803
    jdbc:
      url: jdbc:oracle:thin:@192.168.1.147:1521:XE
      driver: oracle.jdbc.OracleDriver

  hibernate-orm:
    database:
      generation: none
    dialect: org.hibernate.dialect.Oracle10gDialect
    log:
      sql: true

  devservices:
    enabled: false

  swagger-ui:
    always-include: true
    path: /swagger-ui

  smallrye-openapi:
    path: /q/openapi
    info:
      title: Auth Service API
      version: "1.0"
      description: API para autenticación de usuarios en el sistema de inventario

  smallrye-jwt:
    sign:
      key-location: META-INF/privateKey.pem
      algorithm: RS256
    new-token:
      lifespan: 3600

mp:
  jwt:
    verify:
      publickey:
        location: META-INF/publicKey.pem
    issuer: inventario-auth

%dev:
  quarkus:
    devservices:
      enabled: false